# Generated by Django 5.0.6 on 2024-06-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electro', '0004_banner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Electro/static/myapp/img/new'),
        ),
    ]
