# Generated by Django 5.0.6 on 2024-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electro', '0006_banner_link_alter_banner_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='Electro/static/myapp/img/new')),
                ('active', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
