# Generated by Django 5.0.6 on 2024-06-07 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'ordering': ('product', 'brand')},
        ),
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ('product', 'change_date')},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'rating')},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('product', 'user')},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
