# Generated by Django 5.0.6 on 2024-06-10 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_product_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='additionalInform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.additionalinfo'),
        ),
    ]
