# Generated by Django 5.0.6 on 2024-06-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_additionalinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product/statics/rev/'),
        ),
    ]
